K8sManagementApp/ViewModels/NetworkPolicyViewModel.cs
using K8sManagementApp.Models;

namespace K8sManagementApp.ViewModels
{
    public class NetworkPolicyViewModel
    {
        public string Name { get; set; }
        public Dictionary<string, string> Labels { get; set; }
        public List<NetworkPolicyRule> Rules { get; set; }
        public List<string> AvailableApps { get; set; }
    }
}

K8sManagementApp/Controllers/NetworkPolicyController.cs
using k8s;
using k8s.Models;
using K8sManagementApp.Models;
using K8sManagementApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace K8sManagementApp.Controllers
{
    public class NetworkPolicyController : Controller
    {
        private readonly Kubernetes _client;

        public NetworkPolicyController(Kubernetes client)
        {
            _client = client;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var networkPolicies = await _client.ListNamespacedNetworkPolicyAsync("default");
            var networkPolicies = await _client.ListNetworkPolicyForAllNamespacesAsync();
            return View(networkPolicies.Items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NetworkPolicyViewModel model)
        {
            var networkPolicy = new V1NetworkPolicy
            {
                Metadata = new V1ObjectMeta
                {
                    Name = model.Name,
                    Labels = model.Labels
                },
                Spec = new V1NetworkPolicySpec
                {
                    PodSelector = new V1LabelSelector
                    {
                        MatchLabels = model.Labels
                    },
                    Ingress = model.Rules.Select(rule => new V1NetworkPolicyIngressRule
                    {
                        Ports = rule.Ports.Select(port => new V1NetworkPolicyPort
                        {
                            Port = port
                        }).ToList(),
                        FromProperty = rule.Sources.Select(source => new V1NetworkPolicyPeer
                        {
                            PodSelector = new V1LabelSelector
                            {
                                MatchLabels = new Dictionary<string, string>
                            {
                                { "app", source }
                            }
                            }
                        }).ToList()
                    }).ToList()
                }
            };

            await _client.CreateNamespacedNetworkPolicyAsync(networkPolicy, "default");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string name)
        {
            var networkPolicy = await _client.ReadNamespacedNetworkPolicyAsync(name, "default");

            var model = new NetworkPolicyViewModel
            {
                Name = networkPolicy.Metadata.Name,
                Labels = (Dictionary<string, string>)networkPolicy.Metadata.Labels,
                Rules = networkPolicy.Spec.Ingress.Select(rule => new NetworkPolicyRule
                {
                    Ports = rule.Ports.Select(port => port.Port.ToString()).ToList(),
                    Sources = rule.FromProperty.Select(peer => peer.PodSelector.MatchLabels["app"]).ToList(),
                    //Destinations = rule.To.Select(peer => peer.PodSelector.MatchLabels["app"]).ToList()
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string name, NetworkPolicyViewModel model)
        {
            var networkPolicy = await _client.ReadNamespacedNetworkPolicyAsync(name, "default");

            networkPolicy.Metadata.Labels = model.Labels;
            networkPolicy.Spec.PodSelector.MatchLabels = model.Labels;
            networkPolicy.Spec.Ingress = model.Rules.Select(rule => new V1NetworkPolicyIngressRule
            {
                Ports = rule.Ports.Select(port => new V1NetworkPolicyPort
                {
                    Port = int.Parse(port)
                }).ToList(),
                FromProperty = rule.Sources.Select(source => new V1NetworkPolicyPeer
                {
                    PodSelector = new V1LabelSelector
                    {
                        MatchLabels = new Dictionary<string, string>
                {
                    { "app", source }
                }
                    }
                }).ToList()
                ,
                //To = rule.Destinations.Select(destination => new V1NetworkPolicyPeer
                //{
                //    PodSelector = new V1LabelSelector
                //    {
                //        MatchLabels = new Dictionary<string, string>
                //        {
                //            { "app", destination }
                //        }
                //    }
                //}).ToList()
            }).ToList();

            await _client.ReplaceNamespacedNetworkPolicyAsync(networkPolicy, name, "default");

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string name)
        {
            await _client.DeleteNamespacedNetworkPolicyAsync(name, "default");

            return RedirectToAction("Index");
        }
    }
}

K8sManagementApp/Views/NetworkPolicy/Create.cshtml
@using K8sManagementApp.ViewModels
@model NetworkPolicyViewModel

<h2>Create Network Policy</h2>

<form asp-controller="NetworkPolicy" asp-action="Create" method="post" class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label">Name</label>
        <div class="layui-input-block">
            <input type="text" name="Name" lay-verify="required" autocomplete="off" placeholder="Enter the name of the network policy" class="layui-input" value="">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">Rules</label>
        <div class="layui-input-block">
            <table id="rulesTable" class="layui-table" lay-skin="row">
                <colgroup>
                    <col width="40%">
                    <col width="30%">
                    <col width="30%">
                    <col width="10%">
                </colgroup>
                <thead>
                    <tr>
                        <th>Ports</th>
                        <th>Sources</th>
                        <th>Destinations</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <input type="text" name="Rules[0].Ports" lay-verify="required" autocomplete="off" placeholder="Enter the ports" class="layui-input">
                        </td>
                        <td>
                            <select name="Rules[0].Sources" lay-filter="sources" lay-verify="required">
                                <option value="">-</option>
                              @*  @foreach (var app in Model?.AvailableApps)
                                {
                                    <option value="@app">@app</option>
                                }*@
                            </select>
                        </td>
                        <td>
                            <select name="Rules[0].Destinations" lay-filter="destinations" lay-verify="required">
                                <option value="">-</option>
                             @*   @foreach (var app in Model.AvailableApps)
                                {
                                    <option value="@app">@app</option>
                                }*@
                            </select>
                        </td>
                        <td>
                            <button type="button" class="layui-btn layui-btn-sm layui-btn-danger" onclick="$(this).parents('tr').remove()">Remove</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="button" class="layui-btn layui-btn-sm layui-btn-primary" id="addRuleButton">Add rule</button>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="submit" class="layui-btn">Create</button>
        </div>
    </div>
</form>

<script type="text/javascript">
                        layui.use(['form'], function () {
                            var form = layui.form;
                            form.render();

                            $('#addRuleButton').click(function () {
                                var newRow = $('<tr>').append(
                                    $('<td>').append($('<input>').attr({
                                        'type': 'text',
                                        'class': 'layui-input',
                                        'name': 'Rules[' + $('#rulesTable tr').length + '].Ports'
                                    })),
                                    $('<td>').append($('<select>').attr({
                                        'name': 'Rules[' + $('#rulesTable tr').length + '].Sources',
                                        'lay-filter': 'sources'
                                    }).append($('<option>').val('').text('-'))
                                    
                                    /*.append('@@foreach (var app in Model.AvailableApps) {<option value="@@app">@@app</option>}'))*/
                                    ,
                                    $('<td>').append($('<select>').attr({
                                        'name': 'Rules[' + $('#rulesTable tr').length + '].Destinations',
                                        'lay-filter': 'destinations'
                                    }).append($('<option>').val('').text('-'))
                                    //.append('@@foreach (var app in Model.AvailableApps) {<option value="@@app">@@app</option>}'))
                                    ,
                                    $('<td>').append($('<button>').attr({
                                        'type': 'button',
                                        'class': 'layui-btn layui-btn-sm layui-btn-danger'
                                    }).text('Remove').click(function () {
                                        $(this).parents('tr').remove();
                                    }))
                                );

                                $('#rulesTable').append(newRow);
                                form.render('select');
                            });

                            form.on('select(sources)', function (data) {
                                $(data.elem).parents('tr').find('[name$=".Destinations"] option[value="' + data.value + '"]').prop('disabled', true);
                                form.render('select');
                            });

                            form.on('select(destinations)', function (data) {
                                $(data.elem).parents('tr').find('[name$=".Sources"] option[value="' + data.value + '"]').prop('disabled', true);
                                form.render('select');
                            });
                        });
</script>

K8sManagementApp/Views/NetworkPolicy/Edit.cshtml
@using K8sManagementApp.ViewModels
@model NetworkPolicyViewModel

<h2>Edit Network Policy</h2>

<form asp-controller="NetworkPolicy" asp-action="Edit" method="post" class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label">Name</label>
        <div class="layui-input-block">
            <input type="text" name="Name" lay-verify="required" autocomplete="off" placeholder="Enter the name of the network policy" class="layui-input" value="@Model.Name">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">Rules</label>
        <div class="layui-input-block">
            <table id="rulesTable" class="layui-table" lay-skin="row">
                <colgroup>
                    <col width="40%">
                    <col width="30%">
                    <col width="30%">
                    <col width="10%">
                </colgroup>
                <thead>
                    <tr>
                        <th>Ports</th>
                        <th>Sources</th>
                        <th>Destinations</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Rules.Count; i++)
                    {
                        <tr>
                            <td>
                                <input type="text" name="Rules[@i].Ports" lay-verify="required" autocomplete="off" placeholder="Enter the ports" class="layui-input" value="@Model.Rules[i].Ports">
                            </td>
                            <td>
                                <select name="Rules[@i].Sources" lay-filter="sources" lay-verify="required">
                                    <option value="">-</option>
                                    @foreach (var app in Model.AvailableApps)
                                    {
                                      @*  <option value="@app" @{ 
                                            if (Model.Sources == app) { <text>selected</text> } 
                                        }>@app</option>*@

                                        var selected = Model.Rules[@i].Sources.Contains(app) ? "selected" : "";
                                        var optionHtml = $"<option value=\"{app}\" {selected}>{app}</option>";
                                        @Html.Raw(optionHtml)
                                    }
                            </select>
                        </td>
                        <td>
                            <select name="Rules[@i].Destinations" lay-filter="destinations" lay-verify="required">
                                <option value="">-</option>
                                @foreach (var app in Model.AvailableApps)
                                {
                                   @* <option value="@app" @{if (Model.Rules[i].Destinations == app) { <text>selected</text> } }>@app</option>*@
                                   var selected = Model.Rules[@i].Sources.Contains(app) ? "selected" : "";
                                        var optionHtml = $"<option value=\"{app}\" {selected}>{app}</option>";
                                        @Html.Raw(optionHtml)
                                }
                            </select>
                        </td>
                        <td>
                            <button type="button" class="layui-btn layui-btn-sm layui-btn-danger" onclick="$(this).parents('tr').remove()">Remove</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <button type="button" id="addRuleBtn" class="layui-btn layui-btn-sm"><i class="layui-icon">&#xe654;</i> Add rule</button>
    </div>
</div>
<div class="layui-form-item">
    <div class="layui-input-block">
        <button class="layui-btn" lay-submit="" lay-filter="formDemo">Save</button>
        <a asp-controller="NetworkPolicy" asp-action="Index" class="layui-btn layui-btn-primary">Cancel</a>
    </div>
</div>
</form>
@section Scripts {
<script>
layui.use(['form', 'jquery'], function () {
var form = layui.form;
var $ = layui.jquery;
        $('#addRuleBtn').on('click', function () {
            var newRow = $('<tr>').append(
                $('<td>').append($('<input>').attr({
                    'type': 'text',
                    'name': 'Rules[' + $('#rulesTable tr').length + '].Ports',
                    'lay-verify': 'required',
                    'autocomplete': 'off',
                    'placeholder': 'Enter the ports',
                    'class': 'layui-input'
                })),
                $('<td>').append($('<select>').attr({
                    'name': 'Rules[' + $('#rulesTable tr').length + '].Sources',
                    'lay-filter': 'sources',
                    'lay-verify': 'required'
                }).append($('<option>').attr('value', '').text('-'))
                @foreach (var app in Model.AvailableApps)
                {
                    //<text>.append($('<option>').attr('value', '@app').text('@app'))</text>
                   <option value="@app">@app</option>
                }
                ),
                $('<td>').append($('<select>').attr({
                    'name': 'Rules[' + $('#rulesTable tr').length + '].Destinations',
                    'lay-filter': 'destinations',
                    'lay-verify': 'required'
                }).append($('<option>').attr('value', '').text('-'))
                @foreach (var app in Model.AvailableApps)
                {
                    //<text>.append($('<option>').attr('value', '@app').text('@app'))</text>
                     <option value="@app">@app</option>
                }
                ),
                $('<td>').append($('<button>').attr({
                    'type': 'button',
                    'class': 'layui-btn layui-btn-sm layui-btn-danger',
                    'onclick': '$(this).parents("tr").remove()'
                }).text('Remove'))
            );
            $('#rulesTable tbody').append(newRow);
            form.render();
        });

        form.on('select(sources)', function (data) {
            var destinationSelect = $(data.elem).parents('tr').find('[name$=".Destinations"]');
            if (destinationSelect.val() === '') {
                destinationSelect.val(data.value);
                form.render('select');
            }
        });

        form.on('select(destinations)', function (data) {
var sourceSelect = $(data.elem).parents('tr').find('[name$=".Sources"]');
if (sourceSelect.val() === '') {
sourceSelect.val(data.value);
form.render('select');
}
});
});
</script>
}

K8sManagementApp/Views/NetworkPolicy/Index.cshtml
@using k8s.Models
@model IEnumerable<V1NetworkPolicy>

<h2>Network Policies</h2>

<table class="layui-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Labels</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var networkPolicy in Model)
        {
            <tr>
                <td>@networkPolicy.Metadata.Name</td>
                <td>@Json.Serialize(networkPolicy.Metadata.Labels)</td>
                <td>
                    <a class="layui-btn layui-btn-xs layui-btn-normal" href="@Url.Action("Edit", new { name = networkPolicy.Metadata.Name })">Edit</a>
                    <form asp-action="Delete" asp-route-name="@networkPolicy.Metadata.Name" method="post">
                        <button type="submit" class="layui-btn layui-btn-xs layui-btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="layui-btn-container">
    <a class="layui-btn" href="@Url.Action("Create")">Create new network policy</a>
</div>